// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/analytics" | "/assets" | "/build" | "/calendar" | "/companies" | "/companies/[companyId]" | "/companies/[companyId]/intake" | "/companies/[companyId]/integrations" | "/dashboard" | "/integrations" | "/invite/[token]" | "/playground/states" | "/profile" | "/review" | "/select-company" | "/settings" | "/studio" | "/studio/jobs/[jobId]" | "/studio/library"
type AppRouteHandlerRoutes = "/api/assets" | "/api/companies" | "/api/companies/[companyId]" | "/api/companies/[companyId]/context-compile" | "/api/companies/[companyId]/versions" | "/api/context/session" | "/api/inspector/entity" | "/api/search" | "/api/studio/jobs" | "/api/studio/jobs/[jobId]" | "/api/studio/jobs/[jobId]/cancel" | "/api/studio/jobs/[jobId]/route-destination" | "/api/usage/ai" | "/api/usage/ai/consume"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/analytics": {}
  "/api/assets": {}
  "/api/companies": {}
  "/api/companies/[companyId]": { "companyId": string; }
  "/api/companies/[companyId]/context-compile": { "companyId": string; }
  "/api/companies/[companyId]/versions": { "companyId": string; }
  "/api/context/session": {}
  "/api/inspector/entity": {}
  "/api/search": {}
  "/api/studio/jobs": {}
  "/api/studio/jobs/[jobId]": { "jobId": string; }
  "/api/studio/jobs/[jobId]/cancel": { "jobId": string; }
  "/api/studio/jobs/[jobId]/route-destination": { "jobId": string; }
  "/api/usage/ai": {}
  "/api/usage/ai/consume": {}
  "/assets": {}
  "/build": {}
  "/calendar": {}
  "/companies": {}
  "/companies/[companyId]": { "companyId": string; }
  "/companies/[companyId]/intake": { "companyId": string; }
  "/companies/[companyId]/integrations": { "companyId": string; }
  "/dashboard": {}
  "/integrations": {}
  "/invite/[token]": { "token": string; }
  "/playground/states": {}
  "/profile": {}
  "/review": {}
  "/select-company": {}
  "/settings": {}
  "/studio": {}
  "/studio/jobs/[jobId]": { "jobId": string; }
  "/studio/library": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
