// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(app)/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/assets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/assets">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/assets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/build/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/build">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/build/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/calendar">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/companies/[companyId]/intake/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/companies/[companyId]/intake">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/companies/[companyId]/intake/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/companies/[companyId]/integrations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/companies/[companyId]/integrations">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/companies/[companyId]/integrations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/companies/[companyId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/companies/[companyId]">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/companies/[companyId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/companies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/companies">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/companies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/integrations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/integrations">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/integrations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/review/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/review">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/review/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/studio/jobs/[jobId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/studio/jobs/[jobId]">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/studio/jobs/[jobId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/studio/library/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/studio/library">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/studio/library/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/studio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/studio">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/studio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/invite/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invite/[token]">> = Specific
  const handler = {} as typeof import("../../src/app/invite/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/playground/states/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/playground/states">> = Specific
  const handler = {} as typeof import("../../src/app/playground/states/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/select-company/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/select-company">> = Specific
  const handler = {} as typeof import("../../src/app/select-company/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/assets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/assets">> = Specific
  const handler = {} as typeof import("../../src/app/api/assets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/companies/[companyId]/context-compile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/companies/[companyId]/context-compile">> = Specific
  const handler = {} as typeof import("../../src/app/api/companies/[companyId]/context-compile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/companies/[companyId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/companies/[companyId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/companies/[companyId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/companies/[companyId]/versions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/companies/[companyId]/versions">> = Specific
  const handler = {} as typeof import("../../src/app/api/companies/[companyId]/versions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/companies/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/companies">> = Specific
  const handler = {} as typeof import("../../src/app/api/companies/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/context/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/context/session">> = Specific
  const handler = {} as typeof import("../../src/app/api/context/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/inspector/entity/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inspector/entity">> = Specific
  const handler = {} as typeof import("../../src/app/api/inspector/entity/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/search">> = Specific
  const handler = {} as typeof import("../../src/app/api/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/studio/jobs/[jobId]/cancel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/studio/jobs/[jobId]/cancel">> = Specific
  const handler = {} as typeof import("../../src/app/api/studio/jobs/[jobId]/cancel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/studio/jobs/[jobId]/route-destination/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/studio/jobs/[jobId]/route-destination">> = Specific
  const handler = {} as typeof import("../../src/app/api/studio/jobs/[jobId]/route-destination/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/studio/jobs/[jobId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/studio/jobs/[jobId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/studio/jobs/[jobId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/studio/jobs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/studio/jobs">> = Specific
  const handler = {} as typeof import("../../src/app/api/studio/jobs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/usage/ai/consume/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/usage/ai/consume">> = Specific
  const handler = {} as typeof import("../../src/app/api/usage/ai/consume/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/usage/ai/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/usage/ai">> = Specific
  const handler = {} as typeof import("../../src/app/api/usage/ai/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/(app)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
