var R=require("../../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(app)/companies/[companyId]/integrations/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__e89fcea6._.js")
R.c("server/chunks/ssr/_0efddc1b._.js")
R.c("server/chunks/ssr/_7709044e._.js")
R.c("server/chunks/ssr/[root-of-the-server]__22688765._.js")
R.c("server/chunks/ssr/node_modules_next_dist_2e7de858._.js")
R.c("server/chunks/ssr/node_modules_7cb79fa0._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__78b1ec4f._.js")
R.c("server/chunks/ssr/_5b825777._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_2fffaa3a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/src_86a12b2a._.js")
R.c("server/chunks/ssr/ce889_server_app_(app)_companies_[companyId]_integrations_page_actions_cfe9c555.js")
R.m(2197)
module.exports=R.m(2197).exports
